config/routes.rb
Rails.application.routes.draw do
  resources :locations do
    resources :realestates
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :realestates
 
  validates :cities, presence: true, uniqueness: true
  validates :address, presence: true
  
  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:cities, query) -> This would return an exact match of the query
    where("cities like ?", "%#{query}%") 
  end
end

app/models/realestate.rb
class Realestate < ActiveRecord::Base
	belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def index
	    if params[:search]
	      @locations = Location.search(params[:search]).order("created_at DESC")
	    else
	      # @locations = Location.order("created_at DESC")
	      @locations = []
	    end
	
    end

	def show
		@location = Location.find(params[:id])
	end

end

app/controllers/realestates_controller.rb
class RealestatesController < ApplicationController

	def index
		@realestates = Realestate.all
		
	end

	def show

		@realestate = Realestate.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/realestates_helper.rb
module RealestatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrocEstudi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	 <%= form_tag(locations_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Cities" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i>Buscar ahora</button>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<% @locations.each do |location| %>
  <div class="location">
    <h1 class="location-cities"><%= link_to location.cities, location %></h1>
    <p class="location-address"><%= location.address %></p>
  </div>
<% end %>